Add QA-SRL-Bank 2.0 Reader
asyml/forte pull request #246
Opened 2020-09-13 18:17 UTC by ziqian98

This PR fixes [ #231]. 

### Description of changes
A reader for QA-SRL-Bank 2.0 is added.

### Possible influences of this PR.
A new Reader for a new Dataset

### Test Conducted
Three lines of QA-SRL-Bank 2.0 dataset is load and tested.
Unit test Conducted

2020-09-13 19:09 UTC, hunterhector requested changes
Your reader only reads the sentences, where are the questions and labels?

2020-09-13 19:09 UTC, hunterhector commented on forte/data/readers/qasrl_reader.py
> +        The Original data format is somewhat complex, you can find it here:
You don't have to say "this is complex"

2020-09-13 19:10 UTC, hunterhector commented
If this is still a draft, you can convert it into a draft first.

2020-09-13 20:02 UTC, ziqian98 commented on forte/data/readers/qasrl_reader.py
> +        The Original data format is somewhat complex, you can find it here:
Fixed

2020-09-13 20:31 UTC, ziqian98 commented
Each line in the original dataset is like the structure:  https://github.com/uwnlp/qasrl-bank/blob/master/FORMAT.md
I read each line as one sentence, which contains one Question and Semantic Labels.

2020-09-17 17:10 UTC, hunterhector commented
> Each line in the original dataset is like the structure: https://github.com/uwnlp/qasrl-bank/blob/master/FORMAT.md
> I read each line as one sentence, which contains one Question and Semantic Labels.

No, you have to mark Questions and Labels explicitly. Otherwise, when someone is using the reader, how can he know which one is the Question and which one is the Label? What you are doing here is reading plain text only.

2020-09-17 17:14 UTC, hunterhector requested changes
Please explicitly label the Question and Semantic Labels. Ask your teammates if you don't understand what this means. There is so much information in this data format and this reader only gives us the sentence.

2020-09-17 23:13 UTC, ziqian98 commented
> Please explicitly label the Question and Semantic Labels. Ask your teammates if you don't understand what this means. There is so much information in this data format and this reader only gives us the sentence.

I will fix this soon!

2020-09-29 16:19 UTC, hunterhector commented
What's the progress on this?

2020-09-29 18:00 UTC, ziqian98 commented
> What's the progress on this?

Sorry for the late update. I am still testing and will update on this weekend.

2020-10-07 19:23 UTC, hunterhector commented
updates?

2020-10-08 00:56 UTC, ziqian98 commented
> updates?

Something unexpected happened. Still fixing on it all these days.

2020-10-16 08:13 UTC, ziqian98 commented
I extracted the sentenceTokens filed, which is the original sentence, treat it as sentence. 
May I know if the following steps are right:

1. create [ "entry_name": "ft.onto.base_ontology.Question" ...] and [ "entry_name": "ft.onto.base_ontology.Answer" ...]under base_ontology.json
2. create a Question class and a Answer class under base_ontology.py

Using the Question class to read the question generated by the original sentence, and using the  Answer class to read the Answer generated by the original sentence.

2020-11-10 18:32 UTC, hunterhector commented
Do you still want to finish this?

2020-11-10 21:50 UTC, ziqian98 commented
> Do you still want to finish this?

Sorry, I thought this reader was already completed by reading the sentence.
May I know what else should I read except the original sentence?

2020-11-10 21:52 UTC, ziqian98 commented
> Do you still want to finish this?

I talked with my teammates before but they are currently working on NER task and are not sure what to read either.

2020-11-10 22:00 UTC, hunterhector commented
> > Do you still want to finish this?
> 
> I talked with my teammates before but they are currently working on NER task and are not sure what to read either.

The current implementation doesn't record any information from Question and Answer, can you make sure they are in?

2020-11-10 22:14 UTC, ziqian98 commented
Currently, I only read the original Sentence. I was puzzled about how to read the Questions and Answers in the previous comments. I will add this after I finish the Classification task, by the end of the weekday, and before they start the SRL task.

2020-11-10 22:15 UTC, hunterhector commented
> Currently, I only read the original Sentence. I was puzzled about how to read the Questions and Answers in the previous comments. I will add this after I finish the Classification task, by the end of the weekday, and before they start the SRL task.

Yeah. Writing a reader requires you to understand the dataset (and a bit Forte). So you need to understand what this dataset is providing.

2020-12-09 16:53 UTC, closed without merging