add conll03_converter and its unit test
asyml/forte pull request #280
Opened 2020-10-08 20:33 UTC by Jiaqiang-Ruan

This PR fixes [#251]. 

### Description of changes
This pull add a demo converter for NER example and used for a better designed converter module.

### Possible influences of this PR.
Related to the converter design for the framework

### Test Conducted
A unit test is implemented.

2020-10-09 05:59 UTC, jasonyanwenl requested changes
Generally, I think the logic is good. We probably need to sync this implementation with the design. You could find design doc here: https://hackmd.io/@wcqb9QuTQjiwSLy8TexlLg/SkStvAlLP/edit. 
Also, the design is not finalized annd we will discuss this in the meeting.
After we finalized our design, we could change this implementation based on that.

2020-10-09 05:59 UTC, jasonyanwenl commented on forte/data/converter/conll03_converter.py
> +        for sentence in pack.get(Sentence):
We probably could use `pack.get_data(data_request)` to easily query different entries instead of doing this explicitly here.

2020-10-09 05:59 UTC, jasonyanwenl commented on forte/data/converter/conll03_converter.py
> +            yield token_ids, ners_ids
Currently, in my design, the output from converter should be a list of tensors. One entry inside this list corresponding to one instance. Please take a look at this doc for more details: https://hackmd.io/@wcqb9QuTQjiwSLy8TexlLg/SkStvAlLP/edit

2020-10-31 16:36 UTC, closed without merging

2020-10-31 16:36 UTC, Jiaqiang-Ruan commented
Design changes.