create a data selector class for data augmentation
asyml/forte pull request #289
Opened 2020-10-15 07:02 UTC by cz9779

This PR fixes [#288 ]. 

### Description of changes
Create a base data selector class for data augmentation. This class selects datapacks according to a selection criterion. It takes a datapack as input and processes to keep or drop it.
A simple random selector and a simple text length selector are created.

### Test Conducted
A test is created to test the text length selector.

2020-11-03 17:20 UTC, hunterhector requested changes
In addition to the comments inline, please add test cases.

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/base/index_processor2.py
> +class IndexProcessor2(PackProcessor, ABC):
First, just put this into `index_processor.py`. And second, `IndexProcessor2` is not a good name, please rename it to be more meaningful.

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/base/index_processor2.py
> +        compressed_datapack: str = input_pack.serialize()
What is compressed?

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/data_augment/data_select_index_pipeline.py
> +This class is then used by the DataSelector class to search for documents.
You mean `this index`?

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/data_augment/data_select_index_pipeline.py
> +    def _set_data_path(self) -> str:
Why don't we just put this as the `default_config`? And when we use this we simply change the config?

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/data_augment/data_select_index_pipeline.py
> +    def _set_data_path(self) -> str:
Actually, I don't find data source is the best way to use this. The source of data (input parameters) should depend on the implementation of the reader. So we cannot assume that a path is enough. Maybe we can expose the parameters in the `create_index` function?

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/data_augment/data_select_index_pipeline.py
> +                print(f"Indexed {idx + 1} packs")
Use logging instead of print.

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/data_augment/data_select_index_pipeline.py
> +    def __init__(self):
Why don't we directly pass in reader in the parameter?

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/data_augment/data_select_index_pipeline.py
> +        self.create_index()
Here you directly create the index? Can we let the user to call this so they control when to start?

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/data_augment/data_selector_index_processor.py
> +        documents = [{self.config.fields[0]: document[0],
May be you can use better iteration instead of hardcoding the indexes (0,1,2)

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/base/data_selector.py
> +class BaseElasticSearchDataSelector(PackReader):
Can we have a base class to be BaseDataSelector, where the actual implementation such as ElasticSearch is not attached here?

2020-11-03 17:20 UTC, hunterhector commented on forte/processors/base/data_selector.py
> +    according to the search key. It then generate Datapacks.
I think you need to improve the language of the docstring, making it more formal and clear.

2020-11-10 18:31 UTC, hunterhector commented
Updates?

2020-11-10 21:30 UTC, cz9779 commented
> In addition to the comments inline, please add test cases.

I'm wondering how do we add tests for data selector task because the processors are all related to the elastic search indexer that needs to be running...

2020-11-10 22:21 UTC, hunterhector commented
> > In addition to the comments inline, please add test cases.
> 
> I'm wondering how do we add tests for data selector task because the processors are all related to the elastic search indexer that needs to be running...

I think the functionality here is to make sure you can extract some expected results right? So you can create a small index, and try different configurations of your selector (such as random and query based), and make sure the results are correct.

2020-11-16 17:37 UTC, hunterhector approved these changes

2020-11-16 21:20 UTC, merged